In [1]:
!wget https://www.spataru.at/students/course_files/stdm/stocks.csv

--2020-11-23 10:35:07--  https://www.spataru.at/students/course_files/stdm/stocks.csv
Resolving www.spataru.at (www.spataru.at)... 81.19.159.92
Connecting to www.spataru.at (www.spataru.at)|81.19.159.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1125909 (1.1M) [text/csv]
Saving to: ‘stocks.csv’

stocks.csv          100%[===================>]   1.07M   562KB/s    in 2.0s

2020-11-23 10:35:10 (562 KB/s) - ‘stocks.csv’ saved [1125909/1125909]

In [2]:
import pandas as pd
from sklearn.preprocessing import Normalizer
from sklearn.cluster import KMeans
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from  sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from  sklearn.metrics import *
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from sklearn import model_selection
import plotly.express as px

In [4]:
df = pd.read_csv("stocks.csv")

In [5]:
df.head()

         Unnamed: 0  2010-01-04  2010-01-05  ...  2013-10-25  2013-10-28  2013-10-29
0             Apple    0.580000   -0.220005  ...   -5.359962    0.840019  -19.589981
1               AIG   -0.640002   -0.650000  ...   -0.040001   -0.400002    0.660000
2            Amazon   -2.350006    1.260009  ...    4.790009   -1.760009    3.740021
3  American express    0.109997    0.000000  ...    1.849999    0.040001    0.540001
4            Boeing    0.459999    1.770000  ...    1.940002    1.130005    0.309998

[5 rows x 964 columns]